### ISSUE TITLE
启动时遇到如下问题，不知如何解决

### ISSUE THREAD

**Issue by lancer07** [BetterJS/doc#25]
========== badjs-web =========
[2018-05-17 09:28:47.902] [INFO] [default] - running in debug
[2018-05-17 09:28:48.426] [DEBUG] [default] - query url : http://127.0.0.1:9000/query
express-session deprecated undefined resave option; provide resave option badjs-web/workflow/ExpressInitWorker.js:23:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option badjs-web/workflow/ExpressInitWorker.js:23:9
[2018-05-17 09:28:48.686] [INFO] [default] - connect mysql: mysql://root:root@localhost:3306/badjs
[2018-05-17 09:28:48.830] [INFO] [default] - starting mq ...
[2018-05-17 09:28:49.017] [INFO] [default] - create ProcessPool , number : 15
[2018-05-17 09:28:49.021] [INFO] [default] - start badjs-web , listen 8081 ...
[2018-05-17 09:28:49.083] [INFO] [default] - processor(28490) killed 
[2018-05-17 09:28:49.107] [INFO] [default] - processor(28491) killed 
[2018-05-17 09:28:49.108] [INFO] [default] - processor(28492) killed 
[2018-05-17 09:28:49.108] [INFO] [default] - processor(28493) killed 
[2018-05-17 09:28:49.108] [INFO] [default] - processor(28496) killed 

。
。
。
。
。
/opt/root/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:17
                                throw err;
                                      ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
    --------------------
    at Protocol._enqueue (/opt/root/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/opt/root/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/opt/root/badjs-installer/badjs-web/node_modules/mysql/lib/Connection.js:130:18)
    at Driver.connect (/opt/root/badjs-installer/badjs-web/node_modules/orm/lib/Drivers/DML/mysql.js:60:10)
    at Object.exports.connect (/opt/root/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:128:10)
    at Object.module.exports (/opt/root/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:12:6)
    at Object.exports.express (/opt/root/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:39:30)
    at Object.<anonymous> (/opt/root/badjs-installer/badjs-web/workflow/ExpressInitWorker.js:35:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: IPC channel is already disconnected
    at process.target.disconnect (child_process.js:510:26)
    at Worker.disconnect (cluster.js:650:13)
    at Worker.onmessage (cluster.js:541:16)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)

**Comment by loskael** [comment]
你本地的 mysql 正常吗？确认一下 `mysql://root:root@localhost:3306/badjs` 是否可以正常连接
另外， @caihuiji  看一下

**Comment by caihuiji** [comment]
这看起来是mysql 没有链接成功哦

**Comment by ityue** [comment]
调通了吗？遇见同样的问题了？。。。

**Comment by caihuiji** [comment]
这个错误看起来是端口被占用了。
