### ISSUE TITLE
实时日志可以获取到，但是历史记录中没数据；当offlineLog设置为true时，项目报错

### ISSUE THREAD

**Issue by shirleyxyli** [BetterJS/doc#28]
（1）实时日志可以正常获取了，但是历史记录是空的
![image](https://user-images.githubusercontent.com/19338744/46946810-87bb8a80-d0ab-11e8-9820-90b5ad260488.png)

![image](https://user-images.githubusercontent.com/19338744/46946791-7c685f00-d0ab-11e8-817a-87146c682d4f.png)
（2）代码如下
       //初始化
        BJ_REPORT.init({id: 1, uin : 1,repeat:5,url:"http://127.0.0.1/badjs",offlineLog:true});
        BJ_REPORT.offlineLog("offlineLog");
        BJ_REPORT.reportOfflineLog();
        var  mm=1/0;
        var a=b;
报错：
![image](https://user-images.githubusercontent.com/19338744/46946923-d9fcab80-d0ab-11e8-8bbd-f287ccf8f399.png)
跪求大神帮忙

**Comment by shirleyxyli** [comment]
@loskael 
希望大神有空帮忙看看

**Comment by loskael** [comment]
从报错的信息上来看是 https://github.com/BetterJS/badjs-web/blob/10dd7094407bd39e1052977462020b5bf645341f/service/OfflineLogService.js#L59 这里报错了，出错的原因应该是 `fs.writeFile` 的第三个参数必须是一个 `function`, 刚验证了一下`8.x ` 和 `9.x` 的版本会有这个警告
```js
(node:51447) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```
并且 `10.x` 就会报你截图的这个错了
```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:140:9)
    at Object.fs.writeFile (fs.js:1258:14)
```
临时的解决方案可以先降低版本号，只要 `< 10` 就不会报错了，但是会提示上面的 `DeprecationWarning`

@caihuiji  是时候来升级一下了

**Comment by loskael** [comment]
https://github.com/BetterJS/badjs-web/pull/29

**Comment by shirleyxyli** [comment]
@loskael  @caihuiji 
谢谢大神帮助，已经可以获取到离线日志了
但是很奇怪，历史日志和图表统计的数据还是为空的
![image](https://user-images.githubusercontent.com/19338744/46995387-1df2bd80-d14b-11e8-9cac-8ccf2163fb4d.png)

**Comment by shirleyxyli** [comment]
![image](https://user-images.githubusercontent.com/19338744/47007054-f52df080-d169-11e8-90a9-4f2da6243c5c.png)

**Comment by loskael** [comment]
截图的信息不足于判断问题出在哪里

**Comment by shirleyxyli** [comment]
@caihuiji  跪求帮忙看看

**Comment by shirleyxyli** [comment]
@loskael 
![image](https://user-images.githubusercontent.com/19338744/47289161-f9f01a00-d62b-11e8-8768-0d62ff1f02e8.png)

![image](https://user-images.githubusercontent.com/19338744/47289157-f65c9300-d62b-11e8-8c0d-89a94cb7d7ac.png)

![image](https://user-images.githubusercontent.com/19338744/47289151-efce1b80-d62b-11e8-83d6-373f297f17b0.png)

**Comment by shirleyxyli** [comment]
![image](https://user-images.githubusercontent.com/19338744/47289228-4a677780-d62c-11e8-8ae3-607555f8131b.png)

**Comment by shirleyxyli** [comment]
这是代码
![image](https://user-images.githubusercontent.com/19338744/47289283-8995c880-d62c-11e8-9dbd-9dadd87286bc.png)

**Comment by caihuiji** [comment]
图表不是实时统计的，是隔天统计的。
历史日志的问题，你看一下是不是写入mongodb 失败了

**Comment by shirleyxyli** [comment]
@caihuiji 
恩，历史日志问题，我查看是已经连接mongodb成功的喔，但是后面日志中的确没有save到，但是不知道是哪一步少了，会没有写入，实在搞不懂
![image](https://user-images.githubusercontent.com/19338744/47330971-c4d7dc00-d6ac-11e8-8cab-a088373ca217.png)

![image](https://user-images.githubusercontent.com/19338744/47330960-affb4880-d6ac-11e8-85de-00898a0a6d46.png)

**Comment by caihuiji** [comment]
是不是 msg -> storage 这部的数据丢失了。 storage 没有收到数据，这一步可以打一下日志看看

**Comment by shirleyxyli** [comment]
@caihuiji 
请问在哪里可以看到msg->storage??
![image](https://user-images.githubusercontent.com/19338744/47472835-ad325c00-d842-11e8-94c8-5d19b3c9726e.png)

我直接执行test-mongosave.js，发现下面日志错误
![image](https://user-images.githubusercontent.com/19338744/47472809-9429ab00-d842-11e8-960c-a883ffaa23c3.png)
