### ISSUE TITLE
运行badjs-web模块时，总是报一下错，8787端口并没有被占用，求教大佬帮忙瞅瞅

### ISSUE THREAD

**Issue by charliyang** [BetterJS/doc#36]
/Users/charliyang/workspace/BetterJs/badjs-installer-master/badjs-web/node_modules/node-highcharts-exporting/index.js:45
            throw err;
            ^

Error: Command failed: /Users/charliyang/workspace/BetterJs/badjs-installer-master/badjs-web/node_modules/phantomjs/lib/phantom/bin/phantomjs /Users/charliyang/workspace/BetterJs/badjs-installer-master/badjs-web/node_modules/node-highcharts-exporting/lib/highcharts-convert.js -host 127.0.0.1 -port 8787

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: null,
signal: 'SIGSEGV',
  cmd: '/Users/charliyang/workspace/BetterJs/badjs-installer-master/badjs-web/node_modules/phantomjs/lib/phantom/bin/phantomjs /Users/charliyang/workspace/BetterJs/badjs-installer-master/badjs-web/node_modules/node-highcharts-exporting/lib/highcharts-convert.js -host 127.0.0.1 -port 8787'

**Comment by fdliu** [comment]
你这个问题解决了吗
