### ISSUE TITLE
在badjs-accepter目录中执行node app.js --debug  --project报错

### ISSUE THREAD

**Issue by bojbo** [BetterJS/doc#6]
在安装完安装要求中要装的组件后，在badjs-accepter中执行node app.js --debug  --project时报错，报错信息如下：
=>  node app.js --debug  --project  
/home/badjs/badjs-accepter/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/badjs/badjs-accepter/node_modules/zmq/build/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/build/Debug/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/build/Release/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/out/Debug/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/Debug/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/out/Release/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/Release/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/build/default/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/compiled/5.0.0/linux/x64/zmq.node
    at bindings (/home/badjs/badjs-accepter/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/badjs/badjs-accepter/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/badjs/badjs-accepter/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:425:26)
/home/badjs/badjs-accepter/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/badjs/badjs-accepter/node_modules/zmq/build/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/build/Debug/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/build/Release/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/out/Debug/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/Debug/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/out/Release/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/Release/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/build/default/zmq.node
 → /home/badjs/badjs-accepter/node_modules/zmq/compiled/5.0.0/linux/x64/zmq.node
    at bindings (/home/badjs/badjs-accepter/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/badjs/badjs-accepter/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

从报错信息上看应该是zmq的问题，我的zmq是编译安装的。安装时没有报错，应该是安装成功了。

OS：Cenos5.8

**Comment by bojbo** [comment]
楼上报的错应该是zmq没有安装成功，当我再次使用npm install安装的时候，报如下的错误。目前为止还很费解，正在查。。。

[badjs-accepter]# sudo npm install

> zmq@2.13.0 install /home/badjs/badjs-accepter/node_modules/zmq
> node-gyp rebuild

make: Entering directory `/home/badjs/badjs-accepter/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
cc1plus: 错误：无法识别的命令行选项“-std=gnu++0x”
make: *** [Release/obj.target/zmq/binding.o] 错误 1
make: Leaving directory`/home/badjs/badjs-accepter/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node-5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.18-308.el5
gyp ERR! command "/usr/local/node-5.0.0/bin/node" "/usr/local/node-5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/badjs/badjs-accepter/node_modules/zmq
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.18-308.el5
npm ERR! argv "/usr/local/node-5.0.0/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.13.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/badjs/badjs-accepter/npm-debug.log

这个问题到现在我可以确定是zmq没有安装成功。

在更换到ubuntu12.04上之后，npm install可以正常执行

在这里想知道题主是在什么系统上部署的？centos or ubuntu。有没有更详细的针对badjs安装zeromq的说明？

**Comment by loskael** [comment]
@bojbo  我们这边部署机器是 centos 6, 初步看应该是 node-gyp 版本太低了, 参考:
http://webbio.nl/wikiweb/nodejs-node-gyp-build-error-while-installing-extension-cc1plus-error-unrecognized-command-line-option-stdgnu0x/

**Comment by akira-nextday** [comment]
我这里也是报错……依赖应该都装成功了
[2015-12-08 17:55:39.274] [INFO] [default] - start badjs-accepter , listen 80 ...
[2015-12-08 17:55:39.286] [INFO] [default] - start badjs-accepter , listen 80 ...
[2015-12-08 17:55:39.297] [INFO] [default] - start badjs-accepter , listen 80 ...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EACCES
    at exports._errnoException (util.js:746:11)
    at cb (net.js:1195:33)
    at rr (cluster.js:592:14)
    at Worker.<anonymous> (cluster.js:563:9)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
[2015-12-08 17:55:39.324] [INFO] [default] - start badjs-accepter , listen 80 ...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EACCES
    at exports._errnoException (util.js:746:11)
    at cb (net.js:1195:33)
    at rr (cluster.js:592:14)
    at Worker.<anonymous> (cluster.js:563:9)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EACCES
    at exports._errnoException (util.js:746:11)
    at cb (net.js:1195:33)
    at rr (cluster.js:592:14)
    at Worker.<anonymous> (cluster.js:563:9)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EACCES
    at exports._errnoException (util.js:746:11)
    at cb (net.js:1195:33)
    at rr (cluster.js:592:14)
    at Worker.<anonymous> (cluster.js:563:9)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules/connect/lib/middleware/multipart.js:86:15
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: channel closed
    at ChildProcess.target.send (child_process.js:414:26)
    at Worker.send (cluster.js:64:21)
    at dispatchCluster (/home/work/s/badjs-accepter/service/ProjectService.js:20:25)
    at ProjectService (/home/work/s/badjs-accepter/service/ProjectService.js:54:5)
    at null._onTimeout (/home/work/s/badjs-accepter/app.js:37:44)
    at Timer.listOnTimeout (timers.js:110:15)

**Comment by caihuiji** [comment]
新版本已经使用 axon替换了 zmq 。
